No code changes made; skipping commit.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -232,14 +232,6 @@ jobs:
           cache-from: type=registry,ref=nomercyentertainment/ffmpeg-linux-x86_64:buildcache
           cache-to: type=registry,ref=nomercyentertainment/ffmpeg-linux-x86_64:buildcache,mode=max
 
-      - name: Export Linux x86_64 Artifact
-        run: |
-          mkdir -p downloads/linux-x86_64
-          docker pull nomercyentertainment/ffmpeg-linux-x86_64:latest
-          docker create --name linux-x86_64-container nomercyentertainment/ffmpeg-linux-x86_64:latest
-          docker cp linux-x86_64-container:/build/ffmpeg-linux-x86_64-7.1.tar.gz downloads/ffmpeg-linux-x86_64-7.1.tar.gz || echo "File not found in container."
-          docker cp linux-x86_64-container:/build/linux-x86_64 downloads/linux-x86_64 || echo "Directory not found in container."
-          docker rm linux-x86_64-container
           
 
   build-linux-aarch64:
@@ -280,14 +272,6 @@ jobs:
           cache-from: type=registry,ref=nomercyentertainment/ffmpeg-linux-aarch64:buildcache
           cache-to: type=registry,ref=nomercyentertainment/ffmpeg-linux-aarch64:buildcache,mode=max
 
-      - name: Export Linux Aarch64 Artifact
-        run: |
-          mkdir -p downloads/aarch64
-          docker pull nomercyentertainment/ffmpeg-linux-aarch64:latest
-          docker create --name linux-aarch64-container nomercyentertainment/ffmpeg-linux-aarch64:latest
-          docker cp linux-aarch64-container:/build/ffmpeg-linux-aarch64-7.1.tar.gz downloads/ffmpeg-linux-aarch64-7.1.tar.gz || echo "File not found in container."
-          docker cp linux-aarch64-container:/build/aarch64 downloads/aarch64 || echo "Directory not found in container."
-          docker rm linux-aarch64-container
 
   build-windows-x86_64:
     needs: [check-changes, build-base]
@@ -327,14 +311,6 @@ jobs:
           cache-from: type=registry,ref=nomercyentertainment/ffmpeg-windows-x86_64:buildcache
           cache-to: type=registry,ref=nomercyentertainment/ffmpeg-windows-x86_64:buildcache,mode=max
 
-      - name: Export Windows x86_64 Artifact
-        run: |
-          mkdir -p downloads/windows-x86_64
-          docker pull nomercyentertainment/ffmpeg-windows-x86_64:latest
-          docker create --name windows-x86_64-container nomercyentertainment/ffmpeg-windows-x86_64:latest
-          docker cp windows-x86_64-container:/build/ffmpeg-windows-x86_64-7.1.tar.gz downloads/ffmpeg-windows-x86_64-7.1.tar.gz || echo "File not found in container."
-          docker cp windows-x86_64-container:/build/windows downloads/windows-x86_64 || echo "Directory not found in container."
-          docker rm windows-x86_64-container
 
   # build-windows-arch64:
     # needs: [check-changes, build-base]
@@ -374,14 +350,6 @@ jobs:
     #       cache-from: type=registry,ref=nomercyentertainment/ffmpeg-windows-arch64:buildcache
     #       cache-to: type=registry,ref=nomercyentertainment/ffmpeg-windows-arch64:buildcache,mode=max
 
-    #   - name: Export Windows arm64 Artifact
-    #     run: |
-    #       mkdir -p downloads/windows-arm64
-    #       docker pull nomercyentertainment/ffmpeg-windows-arm64:latest
-    #       docker create --name windows-arm64-container nomercyentertainment/ffmpeg-windows-arm64:latest
-    #       docker cp windows-arm64-container:/build/ffmpeg-windows-arm64-7.1.tar.gz downloads/ffmpeg-windows-arm64-7.1.tar.gz || echo "File not found in container."
-    #       docker cp windows-arm64-container:/build/windows downloads/windows-arm64 || echo "Directory not found in container."
-    #       docker rm windows-arm64-container
 
   build-darwin-x86_64:
     needs: [check-changes, build-base]
@@ -421,14 +389,6 @@ jobs:
           cache-from: type=registry,ref=nomercyentertainment/ffmpeg-darwin-x86_64:buildcache
           cache-to: type=registry,ref=nomercyentertainment/ffmpeg-darwin-x86_64:buildcache,mode=max
 
-      - name: Export Darwin x86_64 Artifact
-        run: |
-          mkdir -p downloads/darwin/x86_64
-          docker pull nomercyentertainment/ffmpeg-darwin-x86_64:latest
-          docker create --name darwin-x86_64-container nomercyentertainment/ffmpeg-darwin-x86_64:latest
-          docker cp darwin-x86_64-container:/build/ffmpeg-darwin-x86_64-7.1.tar.gz downloads/ffmpeg-darwin-x86_64-7.1.tar.gz || echo "File not found in container."
-          docker cp darwin-x86_64-container:/build/darwin/x86_64 downloads/darwin/x86_64 || echo "Directory not found in container."
-          docker rm darwin-x86_64-container
 
   build-darwin-arm64:
     needs: [check-changes, build-base]
@@ -468,6 +428,64 @@ jobs:
           cache-from: type=registry,ref=nomercyentertainment/ffmpeg-darwin-arm64:buildcache
           cache-to: type=registry,ref=nomercyentertainment/ffmpeg-darwin-arm64:buildcache,mode=max
 
+          
+  export-artifacts:
+    runs-on: ubuntu-latest
+    needs: [build-linux-x86_64, build-linux-aarch64, build-windows-x86_64, build-darwin-x86_64, build-darwin-arm64, check-changes] #, build-windows-arm64
+    if: needs.check-changes.outputs.base-changed || needs.check-changes.outputs.linux-x86_64-changed || needs.check-changes.outputs.linux-aarch64-changed || needs.check-changes.outputs.windows-x86_64-changed || needs.check-changes.outputs.darwin-x86_64-changed || needs.check-changes.outputs.darwin-arm64-changed || needs.check-changes.outputs.workflow-changed  || github.event.inputs.force_rebuild
+    #|| needs.check-changes.outputs.windows-arm64-changed
+    steps:
+      - name: Log in to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Export Linux x86_64 Artifact
+        run: |
+          mkdir -p downloads/linux-x86_64
+          docker pull nomercyentertainment/ffmpeg-linux-x86_64:latest
+          docker create --name linux-x86_64-container nomercyentertainment/ffmpeg-linux-x86_64:latest
+          docker cp linux-x86_64-container:/build/ffmpeg-linux-x86_64-7.1.tar.gz downloads/ffmpeg-linux-x86_64-7.1.tar.gz || echo "File not found in container."
+          docker cp linux-x86_64-container:/build/linux-x86_64 downloads/linux-x86_64 || echo "Directory not found in container."
+          docker rm linux-x86_64-container
+          
+      - name: Export Linux Aarch64 Artifact
+        run: |
+          mkdir -p downloads/aarch64
+          docker pull nomercyentertainment/ffmpeg-linux-aarch64:latest
+          docker create --name linux-aarch64-container nomercyentertainment/ffmpeg-linux-aarch64:latest
+          docker cp linux-aarch64-container:/build/ffmpeg-linux-aarch64-7.1.tar.gz downloads/ffmpeg-linux-aarch64-7.1.tar.gz || echo "File not found in container."
+          docker cp linux-aarch64-container:/build/aarch64 downloads/aarch64 || echo "Directory not found in container."
+          docker rm linux-aarch64-container
+
+      - name: Export Windows x86_64 Artifact
+        run: |
+          mkdir -p downloads/windows-x86_64
+          docker pull nomercyentertainment/ffmpeg-windows-x86_64:latest
+          docker create --name windows-x86_64-container nomercyentertainment/ffmpeg-windows-x86_64:latest
+          docker cp windows-x86_64-container:/build/ffmpeg-windows-x86_64-7.1.tar.gz downloads/ffmpeg-windows-x86_64-7.1.tar.gz || echo "File not found in container."
+          docker cp windows-x86_64-container:/build/windows downloads/windows-x86_64 || echo "Directory not found in container."
+          docker rm windows-x86_64-container
+
+      # - name: Export Windows arm64 Artifact
+        # run: |
+        #   mkdir -p downloads/windows-arm64
+        #   docker pull nomercyentertainment/ffmpeg-windows-arm64:latest
+        #   docker create --name windows-arm64-container nomercyentertainment/ffmpeg-windows-arm64:latest
+        #   docker cp windows-arm64-container:/build/ffmpeg-windows-arm64-7.1.tar.gz downloads/ffmpeg-windows-arm64-7.1.tar.gz || echo "File not found in container."
+        #   docker cp windows-arm64-container:/build/windows downloads/windows-arm64 || echo "Directory not found in container."
+        #   docker rm windows-arm64-container
+
+      - name: Export Darwin x86_64 Artifact
+        run: |
+          mkdir -p downloads/darwin/x86_64
+          docker pull nomercyentertainment/ffmpeg-darwin-x86_64:latest
+          docker create --name darwin-x86_64-container nomercyentertainment/ffmpeg-darwin-x86_64:latest
+          docker cp darwin-x86_64-container:/build/ffmpeg-darwin-x86_64-7.1.tar.gz downloads/ffmpeg-darwin-x86_64-7.1.tar.gz || echo "File not found in container."
+          docker cp darwin-x86_64-container:/build/darwin/x86_64 downloads/darwin/x86_64 || echo "Directory not found in container."
+          docker rm darwin-x86_64-container
+
       - name: Export Darwin arm64 Artifact
         run: |
           mkdir -p downloads/darwin/arm64
@@ -476,72 +494,6 @@ jobs:
           docker cp darwin-arm64-container:/build/ffmpeg-darwin-arm64-7.1.tar.gz downloads/ffmpeg-darwin-arm64-7.1.tar.gz || echo "File not found in container."
           docker cp darwin-arm64-container:/build/darwin/arm64 downloads/darwin/arm64 || echo "Directory not found in container."
           docker rm darwin-arm64-container
-
-  export-artifacts:
-    runs-on: ubuntu-latest
-    needs: [build-linux-x86_64, build-linux-aarch64, build-windows-x86_64, build-darwin-x86_64, build-darwin-arm64, check-changes] #, build-windows-arm64
-    if: needs.check-changes.outputs.base-changed || needs.check-changes.outputs.linux-x86_64-changed || needs.check-changes.outputs.linux-aarch64-changed || needs.check-changes.outputs.windows-x86_64-changed || needs.check-changes.outputs.darwin-x86_64-changed || needs.check-changes.outputs.darwin-arm64-changed || needs.check-changes.outputs.workflow-changed  || github.event.inputs.force_rebuild
-    #|| needs.check-changes.outputs.windows-arm64-changed
-    steps:
-      # - name: Log in to DockerHub
-      #   uses: docker/login-action@v2
-      #   with:
-      #     username: ${{ secrets.DOCKER_USERNAME }}
-      #     password: ${{ secrets.DOCKER_PASSWORD }}
-
-      # - name: Export Linux x86_64 Artifact
-      #   run: |
-      #     mkdir -p downloads/linux-x86_64
-      #     docker pull nomercyentertainment/ffmpeg-linux-x86_64:latest
-      #     docker create --name linux-x86_64-container nomercyentertainment/ffmpeg-linux-x86_64:latest
-      #     docker cp linux-x86_64-container:/build/ffmpeg-linux-x86_64-7.1.tar.gz downloads/ffmpeg-linux-x86_64-7.1.tar.gz || echo "File not found in container."
-      #     docker cp linux-x86_64-container:/build/linux-x86_64 downloads/linux-x86_64 || echo "Directory not found in container."
-      #     docker rm linux-x86_64-container
-          
-      # - name: Export Linux Aarch64 Artifact
-      #   run: |
-      #     mkdir -p downloads/aarch64
-      #     docker pull nomercyentertainment/ffmpeg-linux-aarch64:latest
-      #     docker create --name linux-aarch64-container nomercyentertainment/ffmpeg-linux-aarch64:latest
-      #     docker cp linux-aarch64-container:/build/ffmpeg-linux-aarch64-7.1.tar.gz downloads/ffmpeg-linux-aarch64-7.1.tar.gz || echo "File not found in container."
-      #     docker cp linux-aarch64-container:/build/aarch64 downloads/aarch64 || echo "Directory not found in container."
-      #     docker rm linux-aarch64-container
-
-      # - name: Export Windows x86_64 Artifact
-      #   run: |
-      #     mkdir -p downloads/windows-x86_64
-      #     docker pull nomercyentertainment/ffmpeg-windows-x86_64:latest
-      #     docker create --name windows-x86_64-container nomercyentertainment/ffmpeg-windows-x86_64:latest
-      #     docker cp windows-x86_64-container:/build/ffmpeg-windows-x86_64-7.1.tar.gz downloads/ffmpeg-windows-x86_64-7.1.tar.gz || echo "File not found in container."
-      #     docker cp windows-x86_64-container:/build/windows downloads/windows-x86_64 || echo "Directory not found in container."
-      #     docker rm windows-x86_64-container
-
-      # # - name: Export Windows arm64 Artifact
-      #   # run: |
-      #   #   mkdir -p downloads/windows-arm64
-      #   #   docker pull nomercyentertainment/ffmpeg-windows-arm64:latest
-      #   #   docker create --name windows-arm64-container nomercyentertainment/ffmpeg-windows-arm64:latest
-      #   #   docker cp windows-arm64-container:/build/ffmpeg-windows-arm64-7.1.tar.gz downloads/ffmpeg-windows-arm64-7.1.tar.gz || echo "File not found in container."
-      #   #   docker cp windows-arm64-container:/build/windows downloads/windows-arm64 || echo "Directory not found in container."
-      #   #   docker rm windows-arm64-container
-
-      # - name: Export Darwin x86_64 Artifact
-      #   run: |
-      #     mkdir -p downloads/darwin/x86_64
-      #     docker pull nomercyentertainment/ffmpeg-darwin-x86_64:latest
-      #     docker create --name darwin-x86_64-container nomercyentertainment/ffmpeg-darwin-x86_64:latest
-      #     docker cp darwin-x86_64-container:/build/ffmpeg-darwin-x86_64-7.1.tar.gz downloads/ffmpeg-darwin-x86_64-7.1.tar.gz || echo "File not found in container."
-      #     docker cp darwin-x86_64-container:/build/darwin/x86_64 downloads/darwin/x86_64 || echo "Directory not found in container."
-      #     docker rm darwin-x86_64-container
-
-      # - name: Export Darwin arm64 Artifact
-      #   run: |
-      #     mkdir -p downloads/darwin/arm64
-      #     docker pull nomercyentertainment/ffmpeg-darwin-arm64:latest
-      #     docker create --name darwin-arm64-container nomercyentertainment/ffmpeg-darwin-arm64:latest
-      #     docker cp darwin-arm64-container:/build/ffmpeg-darwin-arm64-7.1.tar.gz downloads/ffmpeg-darwin-arm64-7.1.tar.gz || echo "File not found in container."
-      #     docker cp darwin-arm64-container:/build/darwin/arm64 downloads/darwin/arm64 || echo "Directory not found in container."
-      #     docker rm darwin-arm64-container
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
